// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using soromaps_api.Data;

#nullable disable

namespace soromaps_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("soromaps_api.Models.Achievement", b =>
                {
                    b.Property<Guid>("AchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("achievement_id");

                    b.Property<string>("AchievementDesc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("achievement_desc");

                    b.Property<string>("AchievementName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("achievement_name");

                    b.HasKey("AchievementId")
                        .HasName("pk_tb_achievements");

                    b.ToTable("tb_achievements", (string)null);
                });

            modelBuilder.Entity("soromaps_api.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("CategoryDesc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category_desc");

                    b.HasKey("CategoryId")
                        .HasName("pk_tb_categorys");

                    b.ToTable("tb_categorys", (string)null);
                });

            modelBuilder.Entity("soromaps_api.Models.Comment", b =>
                {
                    b.Property<Guid>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("comment_id");

                    b.Property<string>("CommentContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment_content");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("CommentId")
                        .HasName("pk_tb_comments");

                    b.HasIndex("ReviewId")
                        .HasDatabaseName("ix_tb_comments_review_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tb_comments_user_id");

                    b.ToTable("tb_comments", (string)null);
                });

            modelBuilder.Entity("soromaps_api.Models.Place", b =>
                {
                    b.Property<Guid>("PlaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("about");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("HasWifi")
                        .HasColumnType("boolean")
                        .HasColumnName("has_wifi");

                    b.Property<float>("Lat")
                        .HasColumnType("real")
                        .HasColumnName("lat");

                    b.Property<float>("Lng")
                        .HasColumnType("real")
                        .HasColumnName("lng");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("neighborhood");

                    b.Property<bool>("PetFriendly")
                        .HasColumnType("boolean")
                        .HasColumnName("pet_friendly");

                    b.Property<string>("PlaceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("place_name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PlaceId")
                        .HasName("pk_tb_places");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_tb_places_author_id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_tb_places_category_id");

                    b.ToTable("tb_places", (string)null);
                });

            modelBuilder.Entity("soromaps_api.Models.Review", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("review_id");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<float>("QtdStars")
                        .HasColumnType("real")
                        .HasColumnName("qtd_stars");

                    b.Property<string>("ReviewContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("review_content");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("ReviewId")
                        .HasName("pk_tb_reviews");

                    b.HasIndex("PlaceId")
                        .HasDatabaseName("ix_tb_reviews_place_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tb_reviews_user_id");

                    b.ToTable("tb_reviews", (string)null);
                });

            modelBuilder.Entity("soromaps_api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Biography")
                        .HasMaxLength(280)
                        .HasColumnType("character varying(280)")
                        .HasColumnName("biography");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Neighborhood")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("neighborhood");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("explorer")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_tb_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_tb_users_email");

                    b.ToTable("tb_users", (string)null);
                });

            modelBuilder.Entity("soromaps_api.Models.Comment", b =>
                {
                    b.HasOne("soromaps_api.Models.Review", "Review")
                        .WithMany()
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tb_comments_reviews_review_id");

                    b.HasOne("soromaps_api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tb_comments_users_user_id");

                    b.Navigation("Review");

                    b.Navigation("User");
                });

            modelBuilder.Entity("soromaps_api.Models.Place", b =>
                {
                    b.HasOne("soromaps_api.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tb_places_users_author_id");

                    b.HasOne("soromaps_api.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tb_places_tb_categorys_category_id");

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("soromaps_api.Models.Review", b =>
                {
                    b.HasOne("soromaps_api.Models.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tb_reviews_tb_places_place_id");

                    b.HasOne("soromaps_api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tb_reviews_users_user_id");

                    b.Navigation("Place");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
